Давыдов ПИм-231

1. Создайте массив arr_1 размером 3х4, все элементы которого равны 3.

In [ ]:
import numpy as np

In [ ]:
arr_1 = np.full((3,4), 3)
print(arr_1)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


2. Создайте массив arr_2, заполненный случайными целыми числами от 0 до
9, размером 2х4.

In [ ]:
arr_2 = np.random.randint(0, 9, (2,4))
print(arr_2)

[[7 2 1 2]
 [6 1 8 1]]


3. Выведите на экран количество элементов в созданных массивах arr_1 и
arr_2.

In [ ]:
print(f"Размер arr_1 {arr_1.size}")
print(f"Размер arr_2 {arr_2.size}")

Размер arr_1 12
Размер arr_2 8


4. Соедините массивы arr_1 и arr_2 по нулевой оси.

In [ ]:
arr_combined = np.concatenate((arr_1, arr_2), axis=0)
print(arr_combined)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [7 2 1 2]
 [6 1 8 1]]


5. Создайте массив arr_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции
np.array().

In [ ]:
arr_3 = np.array([1, 8, 6, 5, 8, 3])
print(arr_3)

[1 8 6 5 8 3]


6. Умножьте каждый элемент массива arr_3 на число 3 и прибавьте к каждому
элементу 1. Результат запишите в новый массив arr_4.

In [ ]:
arr_4 = arr_3 * 3 + 1
print(arr_4)

[ 4 25 19 16 25 10]


7. Преобразуйте масиив arr_3 к двумерному массиву 2х3. Результат запишите
в массив arr_5.

In [ ]:
arr_5 = arr_3.reshape(2, 3)
print(arr_5)

[[1 8 6]
 [5 8 3]]


8. Определите минимальные элементы массива arr_5 вдоль первой оси.

In [ ]:
min_elements = np.min(arr_5, axis=1)
print(min_elements)

[1 3]


9. Вычислите среднее арифметическое всех элементов массива arr_5.

In [ ]:
mean_value = np.mean(arr_5)
print(mean_value)

5.166666666666667


10. Создайте массив arr_6, состоящий из квадратов чисел от 0 до 10.

In [ ]:
arr_6 = np.arange(11) ** 2
print(arr_6)

[  0   1   4   9  16  25  36  49  64  81 100]


11. Выведите каждый второй элемент массива arr_6.

In [ ]:
every_sec_el = arr_6[1::2]
print(every_sec_el)

[ 1  9 25 49 81]


12. Выведите элементы массива arr_6 в обратном порядке.

In [ ]:
reverse_arr_6 = arr_6[::-1]
print(reverse_arr_6)

[100  81  64  49  36  25  16   9   4   1   0]


13. Каждому второму элементу массива arr_6 присвойте значение 2.


In [ ]:
arr_6[1::2] = 2
print(arr_6)

[  0   2   4   2  16   2  36   2  64   2 100]


14. Проверьте, есть ли в массиве arr_6 значение 49.

In [ ]:
are_49_is_here = np.any(arr_6 == 49)
print(are_49_is_here)

False


15. Создайте двумерный массив А, состоящий из положительных и
отрицательных чисел. Из массива A выберите все отрицательные элементы и
запишите их в одномерный массив B.

In [ ]:
A = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
print("Массив A: \n", A, "\n")
B = A[A < 0]
print("Массив B: \n",B)

Массив A: 
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]] 

Массив B: 
 [-2 -4 -6 -8]
